const express=require('express')
const app= express()
const path=require('path')
const mongoose=require('mongoose')
const passport=require('passport')
const flash=require('connect-flash')
const morgan=require('morgan')
const cookieParser=require('cookie-parser')
const bodyParser = require('body-parser')
const session = require( 'express-session')
app.listen(3000, () =>{
  console.log('Corriendo en https://localhost:3000')
})
